pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        try {
        stage('Test') {
            steps {
                sh 'mvn test'
                sh 'mvn site'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        } 
        finally
            {
            step([$class: 'JUnitResultArchiver', testResults: 'target/surefire-reports/TEST-*.xml'])
            }   
    
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
