pipeline {
    agent {
        label 'BuildAgent' 
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        } 
        stage('Test') {
                steps {
                    sh 'mvn test'
                    sh 'mvn site'
                }
                post {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                    regression {
                        step([$class: 'JUnitResultArchiver', testResults: 'target/surefire-reports/TEST-*.xml'])
                    }
                }
            }     
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
